title: "Portafolio de Ayelén"
description: "Analista de sistemas y promotora de la inclusión social."
theme: jekyll-theme-modernist  # O el tema que hayas elegido
author: "Ayelén"
email: "tuemail@ejemplo.com"
twitter_username: ayelen_twitter
github_username: ayerobredo
